import {activities} from './activities.js';
import {categories,moods,energies,names} from './metadata.js';
import {defaults,filterActivities,choose,toggleId,totals,planIssues,similarIdeas,additions,rebuildPlan,replacementOptions,shuffleSample,tallyVotes,timerRemaining,pauseTimer,resumeTimer,recordCompletion} from './logic.js';
import {loadState,persistState,validateActivity,normalizeActivity,previewImport} from './storage.js';
import {escapeHTML as e,button as b,card,filtersView,empty} from './ui.js';
const $=s=>document.querySelector(s);
let storage;try{storage=window.localStorage;}catch{}
const loaded=loadState(storage,activities);const state=loaded.state;
let view='personal',busy=false,previousId=state.plan.mainId,hasSpun=false,search='',round=null,dialogCallback=null,dialogReturn=null,importPreview=null;
const completedAt=new Map();
const catalog=()=>[...activities,...state.custom];
const byId=id=>catalog().find(a=>a.id===id);
const source=()=>state.settings.ownOnly?state.custom:state.settings.includeCustom?catalog():activities;
const planItems=()=>state.plan.ids.map(byId).filter(Boolean);
const f=()=>state.settings.filters;
function persist(){const ok=persistState(storage,state);$('#storage-note').textContent=ok?loaded.warning:'Не вдалося зберегти зміни. Вони працюють у цьому сеансі; не закривайте сторінку, якщо хочете експортувати бібліотеку.';}
function notify(text){$('#notice').textContent=text;if($('#dialog').open){let message=$('#dialog-notice');if(!message){message=document.createElement('p');message.id='dialog-notice';message.className='notice';message.setAttribute('role','status');$('#dialog-content').prepend(message);}message.textContent=text;}}
function focusHeading(selector='#view h2'){const el=$(selector);if(el){el.tabIndex=-1;el.focus({preventScroll:true});}}
function preserveRender(){const focused=document.activeElement;const action=focused?.dataset.action,id=focused?.dataset.id;const details=[...document.querySelectorAll('.extra-filters')].map(d=>d.open);render();document.querySelectorAll('.extra-filters').forEach((d,i)=>{if(details[i])d.open=true;});if(action){const el=[...document.querySelectorAll('#view [data-action]')].find(x=>x.dataset.action===action&&x.dataset.id===id&&!x.disabled);if(el)el.focus({preventScroll:true});else focusHeading();}}
function openDialog(title,body,callback=null){dialogReturn=document.activeElement;dialogCallback=callback;$('#dialog-content').innerHTML=`<div class="dialog-heading"><h2 id="dialog-title">${e(title)}</h2>${b('close-dialog','Закрити ×','','text-button')}</div>${body}`;if(!$('#dialog').open)$('#dialog').showModal();}
function closeDialog(){if($('#dialog').open)$('#dialog').close();dialogCallback=null;}
$('#dialog').addEventListener('close',()=>{if(document.activeElement!==document.body&&!$('#dialog').contains(document.activeElement))return;if(dialogReturn?.isConnected)dialogReturn.focus({preventScroll:true});else focusHeading();});
function confirmAction(title,body,fn){openDialog(title,`<p>${e(body)}</p><div class="actions">${b('confirm','Підтвердити','','primary fit')}${b('close-dialog','Скасувати')}</div>`,fn);}
function standardActions(a,full=false){return `${b('start','Почати',a.id,full?'primary fit':'secondary')}${full?b('complete','Спробував / спробувала',a.id):''}${b('favorite',state.favorites.includes(a.id)?'Прибрати з обраного':'В обране',a.id,'secondary',`aria-pressed="${state.favorites.includes(a.id)}"`)}${b(state.excluded.includes(a.id)?'restore':'exclude',state.excluded.includes(a.id)?'Повернути до рулетки':'Не пропонувати',a.id,'text-button')}`;}
function compact(a,actions='',footer=''){return card(a,{compact:true,actions:actions||b('open','Відкрити →',a.id),favorite:state.favorites.includes(a.id),excluded:state.excluded.includes(a.id),footer});}
function issueView(items=planItems()){const issues=planIssues(items,state.plan.mainId,f(),state.excluded);return issues.length?`<div class="warning" role="status"><strong>План потребує змін</strong><ul>${issues.map(x=>`<li>${e(x)}</li>`).join('')}</ul>${b('rebuild','Перебудувати')}</div>`:'';}
function renderPersonal(){
 const items=planItems(),main=byId(state.plan.mainId),available=filterActivities(source(),f(),state.excluded);
 const result=main?card(main,{actions:`${b('spin','Ще ідею ↗')}${standardActions(main,true)}`,favorite:state.favorites.includes(main.id),excluded:state.excluded.includes(main.id)}):empty(busy?'Обираємо ваш вечір…':hasSpun||!available.length?'Поки що без збігів.':'Хороший вечір починається з «а нумо».',hasSpun||!available.length?'Змініть або скиньте фільтри. Перевірте список виключень і джерело ідей.':'Оберіть умови або довіртеся випадку. Один натиск — одна ідея для вечора.');
 let related='';
 if(main){const similar=similarIdeas(main,source(),f(),state.excluded,state.plan.ids);const extra=additions(main,items,source(),f(),state.excluded);
 related=`${similar.length?`<section class="related"><div class="section-heading"><h2>Схоже</h2><p>Інший варіант замість основної ідеї.</p></div><div class="mini-grid">${similar.map(a=>compact(a,b('select-main','Обрати натомість',a.id))).join('')}</div></section>`:''}${extra.length?`<section class="related"><div class="section-heading"><h2>Добре поєднується</h2><p>Лише якщо хочеться продовження. Доповнення вкладаються у ваші умови.</p></div><div class="mini-grid">${extra.map(a=>compact(a,b('add','Додати до вечора +',a.id))).join('')}</div></section>`:''}`;
 }
 return `<section class="workspace"><div class="filters"><div class="panel-heading"><h2>Ваш вечір, ваші правила</h2>${b('reset','Скинути','','text-button')}</div>${filtersView(f())}<label class="switch-line"><input id="own-only" type="checkbox" ${state.settings.ownOnly?'checked':''}> Лише мої ідеї</label><div class="filter-footer"><p id="match-count">Ідей за вашими умовами: ${available.length}</p>${b('spin',busy?'Обираємо…':'Здивуй мене ↗','','primary',busy?'disabled':'')}<p class="small">Бюджет — умовна оцінка на людину, а не актуальна ціна. «Надворі» означає також поза домом.</p></div></div><div id="result" aria-live="polite" aria-busy="${busy}">${result}</div></section>${main&&items.length===1?issueView(items):''}${items.length>1?renderPlan(items):''}${related}`;
}
function renderPlan(items){const total=totals(items),invalid=planIssues(items,state.plan.mainId,f(),state.excluded).length;
 return `<section class="plan-section"><div class="section-heading"><div><span class="eyebrow">СКЛАДЕНО ВАМИ</span><h2>Мій вечір</h2></div>${b('clear-addons','Очистити доповнення','','text-button')}</div>${issueView(items)}<ol class="plan-list">${items.map((a,i)=>`<li><div class="plan-number">${i+1}</div><div class="plan-info"><strong>${e(a.title)}</strong><small>${a.id===state.plan.mainId?'Основна ідея · ':''}${a.duration} хв · ≈ ${a.cost} грн</small></div><div class="plan-controls">${b('move-up','↑',String(i),'secondary',`aria-label="Перемістити «${e(a.title)}» вище" ${i===0?'disabled':''}`)}${b('move-down','↓',String(i),'secondary',`aria-label="Перемістити «${e(a.title)}» нижче" ${i===items.length-1?'disabled':''}`)}${b('replace-item','Замінити',String(i))}${a.id!==state.plan.mainId?b('remove-addon','Прибрати',a.id,'text-button'):''}</div></li>`).join('')}</ol><div class="plan-summary"><p><strong>${total.duration} хв</strong> послідовно <span>·</span> <strong>≈ ${total.cost} грн / особу</strong><small>Орієнтовний бюджет. Час і вартість усіх пунктів додаються.</small></p>${b('start-plan','Почати план →','','primary fit',invalid?'disabled':'')}</div></section>`;
}
function renderLibrary(){
 const list=state.custom.filter(a=>a.title.toLocaleLowerCase('uk').includes(search.toLocaleLowerCase('uk')));
 return `<section><div class="section-heading"><div><span class="eyebrow">ВАШ ВЛАСНИЙ СПИСОК</span><h2>Мої ідеї</h2><p>Улюблені дрібниці й плани, які знаєте лише ви.</p></div>${b('new-idea','Додати ідею +','','primary fit')}</div><div class="library-toolbar"><label class="search-field">Пошук за назвою<input id="library-search" type="search" value="${e(search)}" placeholder="Наприклад, домашня піца"></label>${b('own-spin','Рулетка моїх ідей')}${b('export','Експорт JSON')}${b('import','Імпорт JSON')}<input type="file" id="import-file" accept="application/json,.json" hidden></div><label class="switch-line"><input id="include-custom" type="checkbox" ${state.settings.includeCustom?'checked':''}> Додавати мої ідеї до загальної рулетки</label><div id="library-results" class="mini-grid">${libraryCards(list)}</div></section>`;
}
function libraryCards(list){return list.length?list.map(a=>compact(a,`${b('open','Відкрити',a.id)}${b('edit-idea','Редагувати',a.id)}${b('delete-idea','Видалити',a.id,'text-button')}`)).join(''):empty(state.custom.length?'Нічого не знайдено':'Тут починається ваша колекція',state.custom.length?'Спробуйте іншу назву.':'Додайте першу ідею: від прогулянки улюбленим маршрутом до сімейного рецепта.');}
function renderCollection(type){const excluded=type==='excluded',ids=excluded?state.excluded:state.favorites,list=catalog().filter(a=>ids.includes(a.id));return `<section><div class="section-heading"><div><h2>${excluded?'Поки що без цих ідей':'На інший хороший вечір'}</h2><p>${excluded?'Поверніть заняття, коли знову будете в настрої.':'Обране та виключення незалежні одне від одного.'}</p></div>${excluded&&list.length?b('restore-all','Повернути всі'):''}</div><div class="mini-grid">${list.length?list.map(a=>compact(a,`${b('open','Відкрити',a.id)}${excluded?b('restore','Повернути',a.id):b('favorite','Прибрати з обраного',a.id)}`)).join(''):empty('Тут поки тихо.',excluded?'Усі заняття доступні для вибору.':'Збережіть ідею кнопкою «В обране» на картці.')}</div></section>`;}
function ratingButtons(h){return `<div class="rating" aria-label="Оцінка заняття">${b('rate','Сподобалось',h.id,'secondary',`data-rating="like" aria-pressed="${h.rating==='like'}"`)}${b('rate','Не моє',h.id,'secondary',`data-rating="dislike" aria-pressed="${h.rating==='dislike'}"`)}</div>`;}
function renderHistory(){return `<section><div class="section-heading"><div><h2>Вечори, що вже сталися</h2><p>Лише завершені заняття. Оцінка «Не моє» не виключає ідею.</p></div>${state.history.length?b('clear-history','Очистити історію','','text-button'):''}</div><div class="mini-grid">${state.history.length?state.history.map(h=>card(h.activity,{compact:true,footer:`<p class="history-date">${e(new Date(h.date).toLocaleString('uk-UA'))}</p>${ratingButtons(h)}`,actions:`${b('history-open','Відкрити',h.id)}${b('delete-history','Видалити запис',h.id,'text-button')}`})).join(''):empty('У кожного вечора своя історія','Натисніть «Спробував / спробувала» або завершіть заняття на екрані виконання.')}</div></section>`;}
function renderGroup(){
 if(!round){const ns=state.settings.participantNames;return `<section><div class="section-heading"><div><span class="eyebrow">ОДИН ПРИСТРІЙ · РІЗНІ СМАКИ</span><h2>Обираємо разом</h2><p>Кожен голосує окремо. Подивимося, де ваші бажання збігаються.</p></div></div><div class="group-setup"><div class="panel"><label class="field">Кількість учасників<select id="participant-count">${[2,3,4,5,6].map(n=>`<option ${n===ns.length?'selected':''}>${n}</option>`).join('')}</select></label><div class="participant-names">${ns.map((n,i)=>`<label class="field">Учасник ${i+1} <small>ім’я необов’язкове</small><input maxlength="60" data-participant="${i}" value="${e(n)}" placeholder="Учасник ${i+1}"></label>`).join('')}</div><p class="muted">Джерело: ${state.settings.ownOnly?'лише мої ідеї':state.settings.includeCustom?'вбудовані та мої ідеї':'вбудовані ідеї'}. Налаштування джерела — у режимі «Для мене».</p><p class="muted">Добірка міститиме до 10 ідей для ${ns.length===2?'двох':'компанії'}. Під час раунду вона не змінюється. Ідеї лише для однієї людини не потрапляють у голосування.</p>${b('start-round','Підготувати добірку →','','primary')}</div><div class="filters"><div class="panel-heading"><h2>Спільні умови</h2>${b('reset-group','Скинути','','text-button')}</div>${filtersView(state.settings.groupFilters,'group')}</div></div></section>`;}
 if(round.phase==='empty')return `<section>${empty('За цими умовами ідей немає','Послабте спільні фільтри або поверніть виключені заняття.')}${b('new-round','Змінити фільтри')}</section>`;
 if(round.phase==='handoff')return `<section class="handoff"><span class="empty-spark" aria-hidden="true">↗</span><span class="eyebrow">УЧАСНИК ${round.person+1} ІЗ ${round.names.length}</span><h2>${round.person?'Передайте пристрій наступному учаснику':'Перший голос — за вами'}</h2><p>${e(round.names[round.person])}, оберіть те, що хочеться саме вам.<br>Попередні голоси залишаться прихованими.</p>${b('begin-voting','Я готовий / готова','','primary fit')}${b('end-round','Завершити раунд','','text-button')}</section>`;
 if(round.phase==='voting'){const a=round.items[round.index];return `<section class="voting"><div class="section-heading"><div><span class="eyebrow">${e(round.names[round.person])}</span><h2>Що вам до душі?</h2><p>Ідея ${round.index+1} із ${round.items.length}</p></div>${b('end-round','Завершити раунд','','text-button')}</div><progress max="${round.items.length}" value="${round.index}"></progress>${card(a,{actions:`${b('vote-yes','Хочу ♥','','primary fit')}${b('vote-no','Пропустити')}`})}</section>`;}
 const results=tallyVotes(round.items,round.votes,round.names.length);const title=results.unanimous.length?'Ось що сподобалося всім':results.max?'Найбільше голосів зібрали':'Цього разу без збігів';
 return `<section><div class="section-heading"><div><span class="eyebrow">РЕЗУЛЬТАТ ГОЛОСУВАННЯ</span><h2>${title}</h2><p>${results.unanimous.length?'Кожен учасник сказав цим ідеям «Хочу».':results.max?'Це лідери голосування, але не одностайний вибір.':'Ніхто не натиснув «Хочу». Змініть фільтри або спробуйте новий раунд.'}</p></div>${b('new-round','Новий раунд')}</div>${results.unanimous.length>1?b('group-random','Випадково серед одностайних ↗','','primary fit'):''}${round.winner?`<p class="group-winner" role="status">Випадок обрав: <strong>${e(round.winner.title)}</strong> ${b('group-open','Відкрити',round.winner.id)}</p>`:''}<div class="mini-grid">${results.top.map(({activity:a,count})=>card(a,{compact:true,footer:`<p class="vote-count">${count} із ${round.names.length} — «Хочу»</p>`,actions:b('group-open','Відкрити ідею',a.id)})).join('')}</div></section>`;
}
function renderExecution(){const run=state.active;if(!run){view='personal';return renderPersonal();}
 if(run.index===run.items.length)return `<section class="execution-summary"><span class="eyebrow">ВЕЧІР У ВАШОМУ ТЕМПІ</span><h2>На сьогодні — ось так.</h2><p>Виконано ${run.statuses.filter(s=>s==='done').length} із ${run.items.length}. Пропущені пункти не записано в історію.</p><ul>${run.items.map((a,i)=>`<li><strong>${e(a.title)}</strong><span>${run.statuses[i]==='done'?'Виконано ✓':'Пропущено'}</span></li>`).join('')}</ul>${b('finish-run','Повернутися до ідей','','primary fit')}</section>`;
 const a=run.items[run.index],done=run.statuses[run.index]==='done',h=state.history.find(x=>x.token===`${run.id}:${run.index}`);
 return `<section class="execution"><div class="section-heading"><div><span class="eyebrow">ЗАРАЗ — ЛИШЕ ЦЕ</span><h2>Пункт ${run.index+1} із ${run.items.length}</h2><p>Виконано: ${run.statuses.filter(s=>s==='done').length} · Пропущено: ${run.statuses.filter(s=>s==='skipped').length}</p></div>${b('leave-execution','Повернутися','','text-button')}</div><progress max="${run.items.length}" value="${run.statuses.filter(s=>s!=='pending').length}"></progress>${card(a,{steps:false})}<div class="execution-tools"><h3>Крок за кроком</h3>${a.things?.length?`<p>Знадобиться: ${a.things.map(e).join(', ')}.</p>`:''}<div class="checklist">${a.steps.map((step,i)=>`<label><input type="checkbox" data-step="${i}" ${run.checks[run.index][i]?'checked':''} ${done?'disabled':''}><span>${e(step)}</span></label>`).join('')}</div><div class="timer-panel"><div><span class="eyebrow">ТАЙМЕР ЗА БАЖАННЯМ</span><output id="timer-display">${formatTime(timerRemaining(run.timer))}</output><span id="timer-status" class="muted">${timerRemaining(run.timer)<=0?'Час сплив. Завершіть заняття, коли будете готові.':run.timer.endAt?'Таймер працює':'Таймер на паузі'}</span></div><div class="actions">${b('timer-toggle',run.timer.endAt?'Пауза':run.timer.remaining===a.duration*60000?'Запустити таймер':'Продовжити','','secondary',done?'disabled':'')}${b('timer-reset','Скинути таймер','','text-button',done?'disabled':'')}</div></div>${done?`<div class="completion-box"><h3>Готово! Заняття в історії.</h3><p>Як вам? Оцінка необов’язкова.</p>${h?ratingButtons(h):''}${b('next-item',run.index===run.items.length-1?'Підсумок вечора →':'Наступний пункт →','','primary fit')}</div>`:`<div class="actions">${b('finish-item','Завершити','','primary fit')}${b('skip-item','Пропустити пункт','','text-button')}</div>`}</div></section>`;
}
function formatTime(ms){const s=Math.ceil(ms/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function render(){
 document.body.classList.toggle('in-execution',view==='execution');
 document.querySelectorAll('[data-action="navigate"]').forEach(el=>{const active=el.dataset.id===view;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});
 for(const key of ['favorites','excluded','history'])$(`#${key}-count`).textContent=state[key].length;
 $('#resume-banner').innerHTML=state.active&&view!=='execution'?`<div class="resume-banner"><div><strong>У вас є незавершений вечір</strong><p>Прогрес збережено на цьому пристрої.</p></div><div class="actions">${b('resume-run','Продовжити')}${b('discard-run','Скинути прогрес','','text-button')}</div></div>`:'';
 $('#view').innerHTML=view==='personal'?renderPersonal():view==='library'?renderLibrary():view==='group'?renderGroup():view==='history'?renderHistory():view==='execution'?renderExecution():renderCollection(view);
 if(busy)$('#view').querySelectorAll('button,input').forEach(el=>el.disabled=true);
}
function setMain(a){
 if(!filterActivities([a],f(),state.excluded).length){notify('Ідея не відповідає поточним фільтрам або виключена. Змініть умови чи поверніть її до рулетки.');return false;}
 const oldMain=state.plan.mainId,extras=planItems().filter(p=>p.id!==oldMain&&p.id!==a.id);
 const rebuilt=rebuildPlan([a,...extras],a.id,source(),f(),state.excluded);
 const removed=extras.filter(x=>!rebuilt.ids.includes(x.id));state.plan=rebuilt;previousId=a.id;hasSpun=true;
 notify(removed.length?`Основну ідею змінено. Прибрано несумісні доповнення: ${removed.map(x=>x.title).join(', ')}.`:'');persist();return true;
}
async function spin(){if(busy)return;const pool=filterActivities(source(),f(),state.excluded);hasSpun=true;if(!pool.length){notify('Немає відповідних ідей. Змініть умови або джерело ідей. Ваш складений план збережено.');render();return;}
 busy=true;render();$('#result')?.classList.add('choosing');await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion: reduce)').matches?0:400));setMain(choose(pool,previousId));busy=false;render();focusHeading('#result h2');if(matchMedia('(max-width:760px)').matches)$('#result').scrollIntoView({block:'start'});
}
function openActivity(a,{history=false,group=false}={}){
 const exists=!!byId(a.id);openDialog(a.title,card(a,{favorite:state.favorites.includes(a.id),excluded:state.excluded.includes(a.id),actions:`${exists?b(group?'group-main':'select-main','Зробити основною ідеєю',a.id,'primary fit'):''}${exists?standardActions(a,true):b(history?'start-history':'start-snapshot','Повторити це заняття',history||a.id)}${!exists?'<p>Це збережений знімок заняття. Оригінал видалено з бібліотеки.</p>':''}`}));
}
function beginRun(items){const start=()=>{state.active={id:crypto.randomUUID(),items:structuredClone(items),index:0,statuses:items.map(()=> 'pending'),checks:items.map(a=>a.steps.map(()=>false)),timer:{remaining:items[0].duration*60000,endAt:null}};view='execution';closeDialog();persist();render();focusHeading();};
 if(state.active)confirmAction('Почати нове виконання?','Поточний активний прогрес буде замінено. Уже завершені заняття залишаться в історії.',start);else start();
}
function directComplete(a){const now=Date.now();if(now-(completedAt.get(a.id)||0)<1500)return;completedAt.set(a.id,now);const token=crypto.randomUUID();state.history=recordCompletion(state.history,a,token,now);persist();render();const h=state.history.find(x=>x.token===token);openDialog('Ще один вечір в історії',`<p>Завершено: <strong>${e(a.title)}</strong>.</p><p>Як вам? Оцінка необов’язкова.</p><div id="rating-dialog">${ratingButtons(h)}</div>${b('close-dialog','Готово','','primary fit')}`);}
function formMarkup(a={}){
 const errors='<span class="field-error"></span>';
 const checkGroup=(key,label,options)=>`<fieldset class="form-group" data-field="${key}"><legend>${label}</legend><div class="checkbox-options">${Object.entries(options).map(([v,t])=>`<label><input type="checkbox" name="${key}" value="${v}" ${a[key]?.includes(v)?'checked':''}> ${e(t)}</label>`).join('')}</div>${errors}</fieldset>`;
 return `<form id="idea-form" data-edit="${e(a.id||'')}" novalidate><div class="form-grid"><label class="field wide" data-field="title">Назва<input name="title" maxlength="160" value="${e(a.title||'')}" required>${errors}</label><label class="field wide" data-field="description">Короткий опис<textarea name="description" maxlength="1200" required>${e(a.description||'')}</textarea>${errors}</label><label class="field" data-field="category">Категорія<select name="category">${Object.entries(categories).map(([v,t])=>`<option value="${v}" ${(a.category||'base')===v?'selected':''}>${e(t)}</option>`).join('')}</select>${errors}</label><label class="field" data-field="energy">Потрібний рівень енергії<select name="energy">${Object.entries(energies).map(([v,t])=>`<option value="${v}" ${String(a.energy||1)===v?'selected':''}>${t}</option>`).join('')}</select>${errors}</label><label class="field" data-field="duration">Тривалість, хв<input name="duration" type="number" min="1" max="10080" step="1" value="${a.duration??''}" required>${errors}</label><label class="field" data-field="cost">Орієнтовний бюджет, грн / особу<input name="cost" type="number" min="0" max="1000000" step="0.01" value="${a.cost??0}" required>${errors}</label></div>${checkGroup('company','Допустима компанія',{solo:names.solo,duo:names.duo,group:names.group})}${checkGroup('places','Місце',{home:names.home,outside:names.outside})}${checkGroup('moods','Настрій',moods)}<label class="field" data-field="things">Потрібні речі <small>необов’язково, кожна з нового рядка</small><textarea name="things">${e(a.things?.join('\n')||'')}</textarea>${errors}</label><label class="field" data-field="steps">Кроки виконання <small>від 1 до 6, кожен з нового рядка</small><textarea name="steps" rows="5" required>${e(a.steps?.join('\n')||'')}</textarea>${errors}</label><div class="actions"><button type="submit" class="primary fit">Зберегти ідею</button>${b('close-dialog','Скасувати')}</div></form>`;
}
const actions={
 'close-dialog':()=>closeDialog(),confirm:()=>{const fn=dialogCallback;closeDialog();fn?.();},
 navigate:id=>{view=id;notify('');render();focusHeading();},
 spin:()=>spin(),reset:()=>{state.settings.filters={...defaults};persist();render();notify('Фільтри скинуто.');},
 'reset-group':()=>{state.settings.groupFilters={...defaults};persist();render();},
 favorite:id=>{state.favorites=toggleId(state.favorites,id);persist();preserveRender();if($('#dialog').open){const a=byId(id);if(a&&$('#dialog-content .idea'))openActivity(a);}},
 exclude:id=>{state.excluded=[...new Set([...state.excluded,id])];if(state.plan.mainId===id){const next=choose(filterActivities(source(),f(),state.excluded),id);if(next)setMain(next);else state.plan={mainId:null,ids:[]};}persist();closeDialog();preserveRender();notify('Ідею виключено. В обраному вона залишається.');},
 restore:id=>{state.excluded=state.excluded.filter(x=>x!==id);persist();closeDialog();preserveRender();notify('Ідея знову бере участь у виборі.');},
 'restore-all':()=>{state.excluded=[];persist();preserveRender();},
 open:id=>openActivity(byId(id)),
 'select-main':id=>{const a=byId(id);if(a&&setMain(a)){closeDialog();view='personal';render();focusHeading('#result h2');}},
 add:id=>{const a=byId(id),main=byId(state.plan.mainId);if(!a||!main||!additions(main,planItems(),source(),f(),state.excluded).some(x=>x.id===id)){notify('Це доповнення вже недоступне за поточними умовами.');return;}state.plan.ids.push(id);persist();render();notify('Доповнення додано до «Мого вечора».');focusHeading('.plan-section h2');},
 'remove-addon':id=>{state.plan.ids=state.plan.ids.filter(x=>x!==id);persist();preserveRender();},
 'clear-addons':()=>{state.plan.ids=state.plan.mainId?[state.plan.mainId]:[];persist();render();focusHeading();},
 'move-up':id=>moveItem(Number(id),-1),'move-down':id=>moveItem(Number(id),1),
 rebuild:()=>{const old=state.plan.ids.length;state.plan=rebuildPlan(planItems(),state.plan.mainId,source(),f(),state.excluded);persist();render();notify(`План перебудовано. Залишилося пунктів: ${state.plan.ids.length}${old>state.plan.ids.length?`; прибрано: ${old-state.plan.ids.length}`:''}.`);},
 'replace-item':id=>{const options=replacementOptions(planItems(),Number(id),state.plan.mainId,source(),f(),state.excluded);openDialog('Замінити пункт вечора',options.length?`<div class="mini-grid">${options.map(a=>compact(a,b('apply-replacement','Обрати',a.id,'secondary',`data-index="${id}"`))).join('')}</div>`:'<p>Немає сумісної заміни, що вкладається в умови всього плану. Можна змінити фільтри або прибрати цей пункт.</p>');},
 'apply-replacement':(id,el)=>{const index=Number(el.dataset.index),a=byId(id);if(!replacementOptions(planItems(),index,state.plan.mainId,source(),f(),state.excluded).some(x=>x.id===id))return;if(state.plan.ids[index]===state.plan.mainId)state.plan.mainId=id;state.plan.ids[index]=id;persist();closeDialog();render();notify(`Пункт замінено на «${a.title}».`);},
 start:id=>{const a=byId(id);if(a)beginRun([a]);},'start-plan':()=>{if(!planIssues(planItems(),state.plan.mainId,f(),state.excluded).length)beginRun(planItems());},
 complete:id=>{const a=byId(id);if(a)directComplete(a);},
 'resume-run':()=>{view='execution';render();focusHeading();},
 'discard-run':()=>confirmAction('Скинути активний прогрес?','Позначені кроки й таймер буде скинуто. Уже завершені заняття залишаться в історії.',()=>{state.active=null;persist();render();}),
 'leave-execution':()=>{view='personal';persist();render();focusHeading();},
 'timer-toggle':()=>{const run=state.active;if(!run||run.statuses[run.index]!=='pending')return;run.timer=run.timer.endAt?pauseTimer(run.timer):resumeTimer(run.timer);persist();preserveRender();},
 'timer-reset':()=>{const run=state.active;if(!run||run.statuses[run.index]!=='pending')return;run.timer={remaining:run.items[run.index].duration*60000,endAt:null};persist();preserveRender();},
 'finish-item':()=>{const run=state.active;if(!run||run.statuses[run.index]!=='pending')return;const token=`${run.id}:${run.index}`;state.history=recordCompletion(state.history,run.items[run.index],token);run.statuses[run.index]='done';run.timer=pauseTimer(run.timer);persist();render();focusHeading('.completion-box h3');},
 'skip-item':()=>{const run=state.active;if(!run||run.statuses[run.index]!=='pending')return;run.statuses[run.index]='skipped';advanceRun();},
 'next-item':()=>{if(state.active?.statuses[state.active.index]==='done')advanceRun();},
 'finish-run':()=>{state.active=null;view='personal';persist();render();focusHeading();},
 rate:(id,el)=>{const h=state.history.find(x=>x.id===id);if(!h)return;h.rating=el.dataset.rating;persist();if($('#rating-dialog'))$('#rating-dialog').innerHTML=ratingButtons(h);else preserveRender();notify('Оцінку збережено.');},
 'history-open':id=>{const h=state.history.find(x=>x.id===id);if(h)openActivity(h.activity,{history:id});},
 'start-snapshot':id=>{const a=round?.items.find(x=>x.id===id);if(a)beginRun([a]);},
 'start-history':id=>{const h=state.history.find(x=>x.id===id);if(h)beginRun([h.activity]);},
 'delete-history':id=>{state.history=state.history.filter(x=>x.id!==id);persist();preserveRender();},
 'clear-history':()=>confirmAction('Очистити історію?','Усі записи виконання й оцінки буде видалено. Бібліотека та обране залишаться.',()=>{state.history=[];persist();render();}),
 'new-idea':()=>openDialog('Нова ідея для вечора',formMarkup()),
 'edit-idea':id=>{const a=state.custom.find(x=>x.id===id);if(a)openDialog('Редагувати ідею',formMarkup(a));},
 'delete-idea':id=>{const a=byId(id);confirmAction('Видалити власну ідею?',`«${a.title}» буде видалено з бібліотеки, обраного, виключень і плану. Знімки в історії та активне виконання збережуться.`,()=>{state.custom=state.custom.filter(x=>x.id!==id);state.favorites=state.favorites.filter(x=>x!==id);state.excluded=state.excluded.filter(x=>x!==id);state.plan.ids=state.plan.ids.filter(x=>x!==id);if(state.plan.mainId===id)state.plan={mainId:null,ids:[]};persist();render();});},
 'own-spin':()=>{state.settings.ownOnly=true;view='personal';persist();spin();},
 export:()=>{const blob=new Blob([JSON.stringify({version:2,activities:state.custom},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='moi-idei.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Бібліотеку експортовано у JSON.');},
 import:()=>$('#import-file').click(),
 'apply-import':()=>{if(!importPreview)return;const existing=new Set(catalog().map(a=>a.id));const added=importPreview.added.filter(a=>!existing.has(a.id));state.custom.push(...added);importPreview=null;persist();closeDialog();render();notify(`Додано власних ідей: ${added.length}. Наявні записи не змінено.`);},
 'start-round':()=>{const count=state.settings.participantNames.length,shared=state.settings.groupFilters;const pool=filterActivities(source(),shared,state.excluded).filter(a=>a.company.includes(count===2?'duo':'group'));round={phase:pool.length?'handoff':'empty',items:structuredClone(shuffleSample(pool)),names:state.settings.participantNames.map((n,i)=>n.trim()||`Учасник ${i+1}`),votes:Array.from({length:count},()=>[]),person:0,index:0,filters:{...shared},winner:null};render();focusHeading();},
 'begin-voting':()=>{if(round?.phase==='handoff'){round.phase='voting';round.index=0;render();focusHeading();}},
 'vote-yes':()=>vote(true),'vote-no':()=>vote(false),
 'end-round':()=>confirmAction('Завершити цей раунд?','Поточні голоси буде скинуто. Спільні фільтри й імена залишаться.',()=>{round=null;render();}),
 'new-round':()=>{round=null;render();focusHeading();},
 'group-random':()=>{const pool=tallyVotes(round.items,round.votes,round.names.length).unanimous.map(x=>x.activity);round.winner=choose(pool,round.winner?.id);render();focusHeading();},
 'group-open':id=>{const a=round?.items.find(x=>x.id===id);if(a)openActivity(a,{group:true});},
 'group-main':id=>{const a=byId(id);if(!a)return;state.settings.filters={...round.filters,company:round.names.length===2?'duo':'group'};if(setMain(a)){closeDialog();view='personal';render();focusHeading('#result h2');}}
};
function moveItem(index,direction){const next=index+direction;if(next<0||next>=state.plan.ids.length)return;[state.plan.ids[index],state.plan.ids[next]]=[state.plan.ids[next],state.plan.ids[index]];persist();render();const el=[...document.querySelectorAll(`[data-action="move-${direction===-1?'up':'down'}"]`)].find(x=>Number(x.dataset.id)===next&&!x.disabled);if(el)el.focus();else focusHeading('.plan-section h2');}
function advanceRun(){const run=state.active;run.index++;run.timer={remaining:(run.items[run.index]?.duration||0)*60000,endAt:null};persist();render();focusHeading();}
let voteLock=0;
function vote(want){if(!round||round.phase!=='voting'||Date.now()<voteLock)return;voteLock=Date.now()+250;if(want)round.votes[round.person].push(round.items[round.index].id);round.index++;if(round.index===round.items.length){round.person++;round.phase=round.person===round.names.length?'results':'handoff';round.index=0;}render();focusHeading();}
// Delegation keeps imported strings inert: every content interpolation passes through escapeHTML.
let mutationLock=0;
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled||busy)return;const {action,id}=el.dataset;if(['skip-item','next-item','finish-run'].includes(action)){if(Date.now()<mutationLock)return;mutationLock=Date.now()+300;}actions[action]?.(id,el);});
document.addEventListener('change',event=>{
 const el=event.target;if(el.dataset.filter){const key=el.dataset.filter,group=el.dataset.scope==='group',target=group?state.settings.groupFilters:f();target[key]=['time','budget','energy'].includes(key)?Number(el.value):el.value;const name=el.name,value=el.value,wasOpen=el.closest('details')?.open;persist();render();const replacement=[...document.querySelectorAll('input[data-filter]')].find(x=>x.name===name&&x.value===value);if(replacement){if(wasOpen)replacement.closest('details').open=true;replacement.focus({preventScroll:true});}return;}
 if(el.id==='include-custom'||el.id==='own-only'){state.settings[el.id==='include-custom'?'includeCustom':'ownOnly']=el.checked;persist();preserveRender();}
 if(el.id==='participant-count'){const count=Number(el.value);state.settings.participantNames=Array.from({length:count},(_,i)=>state.settings.participantNames[i]||'');persist();render();$('#participant-count').focus();}
 if(el.dataset.participant!==undefined){state.settings.participantNames[Number(el.dataset.participant)]=el.value;persist();}
 if(el.dataset.step!==undefined&&state.active){state.active.checks[state.active.index][Number(el.dataset.step)]=el.checked;persist();}
 if(el.id==='import-file')readImport(el.files[0]);
});
document.addEventListener('input',event=>{if(event.target.id==='library-search'){search=event.target.value;$('#library-results').innerHTML=libraryCards(state.custom.filter(a=>a.title.toLocaleLowerCase('uk').includes(search.toLocaleLowerCase('uk'))));}});
document.addEventListener('submit',event=>{
 if(event.target.id!=='idea-form')return;event.preventDefault();const form=event.target,data=new FormData(form),id=form.dataset.edit||`custom-${crypto.randomUUID()}`;
 const lines=key=>String(data.get(key)||'').split('\n').map(s=>s.trim()).filter(Boolean);
 const a={id,title:data.get('title'),description:data.get('description'),category:data.get('category'),duration:data.get('duration')===''?NaN:Number(data.get('duration')),cost:data.get('cost')===''?NaN:Number(data.get('cost')),energy:Number(data.get('energy')),company:data.getAll('company'),places:data.getAll('places'),moods:data.getAll('moods'),things:lines('things'),steps:lines('steps')};
 const validation=validateActivity(a);form.querySelectorAll('[data-field]').forEach(wrapper=>{const key=wrapper.dataset.field,error=validation.errors[key],msg=wrapper.querySelector('.field-error');msg.id=`error-${key}`;msg.textContent=error||'';wrapper.querySelectorAll('input,textarea,select').forEach(input=>{input.setAttribute('aria-invalid',String(!!error));input.setAttribute('aria-describedby',msg.id);});});
 if(!validation.valid){form.querySelector('[aria-invalid="true"]')?.focus();return;}
 const normalized=normalizeActivity(a),index=state.custom.findIndex(x=>x.id===id);if(index>=0)state.custom[index]=normalized;else state.custom.push(normalized);persist();closeDialog();render();notify('Ідею збережено. Якщо вона входить до плану, його сумісність перевірено повторно.');focusHeading();
});
async function readImport(file){if(!file)return;if(file.size>2*1024*1024){notify('Файл завеликий. Максимальний розмір — 2 МБ.');return;}try{importPreview=previewImport(await file.text(),catalog());if(importPreview.error){openDialog('Імпорт не застосовано',`<p>${e(importPreview.error)}</p>`);return;}openDialog('Перевірте імпорт',`<p>Нових: <strong>${importPreview.added.length}</strong>. Пропущених через однаковий id: <strong>${importPreview.skipped}</strong>. Некоректних: <strong>${importPreview.invalid}</strong>.</p><p>Наявна бібліотека не буде перезаписана. Буде додано лише коректні нові заняття.</p><div class="actions">${b('apply-import','Додати до бібліотеки','','primary fit',importPreview.added.length?'':'disabled')}${b('close-dialog','Скасувати')}</div>`);}catch{notify('Не вдалося прочитати файл. Бібліотеку не змінено.');}}
setInterval(()=>{if(view!=='execution'||!state.active||!$('#timer-display'))return;const left=timerRemaining(state.active.timer);$('#timer-display').textContent=formatTime(left);$('#timer-status').textContent=left<=0?'Час сплив. Завершіть заняття, коли будете готові.':state.active.timer.endAt?'Таймер працює':'Таймер на паузі';},500);
render();persist();
